Repository opaque-systems/opaquegateway-python, pull requests merged in 2023-08, with the labels that each got.

#16 atls: use atls instead of pyatls
  python-package-prompt-guard/src/promptguard/promptguard_service.py
Labels: refactor

#15 docs: add readthedocs link to README
  README.md
  docs/reference/library_api.md
  docs/spelling_wordlist.txt
  mkdocs.yml
Labels: docs

#18 style: Rename python-package-prompt-guard to python-package
  docs/reference/library_api.md
  python-package/LICENSE
  python-package/README.md
  python-package/dist/promptguard-0.1.8-py3-none-any.whl
  python-package/dist/promptguard-0.1.8.tar.gz
  python-package/pyproject.toml
  python-package/setup.py
  python-package/src/promptguard/__init__.py
  python-package/src/promptguard/authentication.py
  python-package/src/promptguard/configuration.py
  python-package/src/promptguard/promptguard_service.py
Labels: style

#20 docs: Add docstrings to response dataclasses
  docs/reference/library_api.md
  python-package/dist/promptguard-0.1.8-py3-none-any.whl
  python-package/dist/promptguard-0.1.8.tar.gz
  python-package/src/promptguard/promptguard_service.py
Labels: docs

#22 use requests with attested connection pooling
  python-package/src/promptguard/promptguard_service.py
Labels: feat

#24 docs: Bump version to 0.0.3
  python-package/pyproject.toml
Labels: docs

#25 docs: rename promptguard to opaqueprompts
  README.md
  docs/getting_started/quickstart.md
  docs/index.md
  docs/spelling_wordlist.txt
  mkdocs.yml
  python-package/README.md
Labels: docs

#27 refactor: rename
  docs/reference/library_api.md
  docs/spelling_wordlist.txt
  python-package/pyproject.toml
  python-package/setup.py
  python-package/src/opaqueprompts/__init__.py
  python-package/src/opaqueprompts/authentication.py
  python-package/src/opaqueprompts/configuration.py
  python-package/src/opaqueprompts/opaqueprompts_service.py
Labels: refactor
