Repository opaque-systems/opaquegateway-python, pull requests merged in 2023-09, with the labels that each got.

#31 build: upgrade pyatls
  python-package/pyproject.toml
Labels: build

#32 fix: change the default host
  python-package/pyproject.toml
  python-package/src/opaqueprompts/configuration.py
Labels: fix

#39 docs: Fix Discord link in README
  README.md
  docs/index.md
Labels: docs

#42 atls: fix disable via environment variable
  python-package/src/opaqueprompts/opaqueprompts_service.py
Labels: fix
